### ISSUE TITLE
Colab example is not working

### ISSUE THREAD

**Issue by SkalskiP** [camenduru/Qwen-VL-Chat-colab#6]
Hi! 👋🏻 I just tried to run your Google [Colab](https://colab.research.google.com/github/camenduru/Qwen-VL-Chat-colab/blob/main/Qwen_VL_Chat_colab.ipynb).

Unfortunately, I got an exception:

```
Traceback (most recent call last):
  File "/content/app.py", line 245, in <module>
    main()
  File "/content/app.py", line 241, in main
    _launch_demo(args, model, tokenizer)
  File "/content/app.py", line 203, in _launch_demo
    chatbot = gr.Chatbot(label='Qwen-VL-Chat', elem_classes="control-height").style(height=500)
AttributeError: 'Chatbot' object has no attribute 'style'. Did you mean: 'scale'?
```

**Comment by camenduru** [comment]
thanks for the info ❤ please try again
